### ISSUE TITLE
Failing on current nightly

### ISSUE THREAD

**Issue by whatisinternet** [whatisinternet/Inflector#51]
Looks like we have some either dead macros or unused macros. We should get this fixed ASAP.

**Comment by theduke** [comment]
The problem is the macros for case tests which are not used when not compiling the tests.

**Comment by whatisinternet** [comment]
Thanks! I haven't really had time to look into it yet so I appreciate the help. If you're up to it I'd be open to approaches for fixing the warning and PRs. 

The easy solution is to ignore the warnings for now with `#[allow(unused_macros)]`. It's obviously not ideal since really the macros should be either moved to codegen (or something) or replaced with non-macro implementations.

**Comment by theduke** [comment]
I would move the macros to a test only module.

```rust
#[cfg(test)]
mod test_macros {
  ...
}
```
