### ISSUE TITLE
Register other cases with crates.io

### ISSUE THREAD

**Issue by OJFord** [whatisinternet/Inflector#52]
I've never submitted a crate, so I don't know that it's possible, but after spending a few minutes wondering why on Earth cargo wasn't finding `inflector = x` - for `x` as anything I could think to try - I think it would be a great idea to register 'inflector' as an alias for the crate 'Inflector', if that's possible?

If it's not possible, then perhaps consider changing the repo name to 'Inflector', so they're at least consistent?

**Comment by whatisinternet** [comment]
Changed the repo name to `Inflector` instead of `inflector`. Thanks for the feedback, I honestly thought that I had named them the same.
