### ISSUE TITLE
Incorrect singularize result for "access"

### ISSUE THREAD

**Issue by nbaksalyar** [whatisinternet/Inflector#59]
`to_singular()` produces an incorrect result for string `access`: `acce`.

Expected result: `access`

**Comment by whatisinternet** [comment]
Thanks for the report! That seems like a problem. Did you want to try and fix it or just reporting? Let me know if it's urgent otherwise I'll have a look at it over the weekend.

**Comment by nbaksalyar** [comment]
I can fix this. Thanks! :)

**Comment by whatisinternet** [comment]
Fixed by #60 and released as [0.11.1](https://crates.io/crates/Inflector/0.11.1)
