### ISSUE TITLE
ClassCase singularization

### ISSUE THREAD

**Issue by Yoric** [whatisinternet/Inflector#61]
The documentation should make clear that `to_class_case` singularizes the string.

Also, it would be nice if there was a variant that does not singularize. I'll be happy to work on a PR if someone finds a good name for the function/module :)

**Comment by whatisinternet** [comment]
@Yoric :wave: I'm not sure why I didn't catch this at the time but I'm pretty sure `to_pascal_case` will actually do exactly what you're looking for with the current version. I'll likely back out the classes_case change this weekend and publish a new version `0.11.2` just to update my dependencies. Let me know if that works for you or if you need a hand updating your code to accommodate the change.

**Comment by whatisinternet** [comment]
https://github.com/whatisinternet/Inflector/blob/master/src/cases/pascalcase/mod.rs for reference

**Comment by Yoric** [comment]
You're right, I missed this, sorry about that!

**Comment by whatisinternet** [comment]
All good! Thanks for the help none the less. :tada:

**Comment by RReverser** [comment]
Omg, so *that's* why `os` was transformed to `O`. Wasn't sure why it's losing a letter and was worried about some off-by-one error.

**Comment by whatisinternet** [comment]
Sorry about that! Would you like to take a shot at updating the documentation to make it clearer?
